import json
import re
import socket
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any, Dict, List


DEFAULT_INTEGRATION: Dict[str, Any] = {
    "mode": "local",
    "endpoint": "",
    "apiKey": "",
    "apiKeyHeader": "Authorization",
    "apiKeyPrefix": "Bearer ",
    "customHeaders": "",
    "workflowPayload": "flat",
    "model": "gpt-4.1-mini",
    "timeoutSec": 90,
    "fallbackToLocal": True,
}


def load_integration_config(config_path: Path) -> Dict[str, Any]:
    if not config_path.exists():
        return dict(DEFAULT_INTEGRATION)
    try:
        data = json.loads(config_path.read_text(encoding="utf-8-sig"))
    except Exception:
        return dict(DEFAULT_INTEGRATION)
    config = dict(DEFAULT_INTEGRATION)
    for key in DEFAULT_INTEGRATION:
        if key in data:
            config[key] = data[key]
    config["timeoutSec"] = normalize_timeout(config.get("timeoutSec"))
    config["fallbackToLocal"] = bool(config.get("fallbackToLocal", True))
    if config.get("mode") not in {"local", "workflow_api", "ai_api"}:
        config["mode"] = "local"
    if config.get("apiKeyHeader") not in {"Authorization", "X-API-Key", "api-key", "none"}:
        config["apiKeyHeader"] = "Authorization"
    if config.get("workflowPayload") not in {"flat", "input", "dify"}:
        config["workflowPayload"] = "flat"
    return config


def save_integration_config(config_path: Path, patch: Dict[str, Any]) -> Dict[str, Any]:
    current = load_integration_config(config_path)
    if patch.get("clearApiKey"):
        current["apiKey"] = ""
    for key in DEFAULT_INTEGRATION:
        if key in patch:
            value = patch[key]
            if key == "apiKey" and value == "":
                continue
            current[key] = value
    current["timeoutSec"] = normalize_timeout(current.get("timeoutSec"))
    current["fallbackToLocal"] = bool(current.get("fallbackToLocal", True))
    if current.get("mode") not in {"local", "workflow_api", "ai_api"}:
        current["mode"] = "local"
    if current.get("apiKeyHeader") not in {"Authorization", "X-API-Key", "api-key", "none"}:
        current["apiKeyHeader"] = "Authorization"
    if current.get("workflowPayload") not in {"flat", "input", "dify"}:
        current["workflowPayload"] = "flat"
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(json.dumps(current, ensure_ascii=False, indent=2), encoding="utf-8-sig")
    return current


def public_integration_config(config: Dict[str, Any]) -> Dict[str, Any]:
    public = {key: config.get(key, DEFAULT_INTEGRATION[key]) for key in DEFAULT_INTEGRATION if key != "apiKey"}
    key = str(config.get("apiKey") or "")
    public["hasApiKey"] = bool(key)
    public["apiKeyMasked"] = mask_key(key)
    return public


def mask_key(key: str) -> str:
    if not key:
        return ""
    if len(key) <= 8:
        return "*" * len(key)
    return f"{key[:4]}...{key[-4:]}"


def normalize_timeout(value: Any) -> int:
    try:
        timeout = int(value)
    except Exception:
        timeout = 90
    return max(10, min(timeout, 600))


def should_use_external(config: Dict[str, Any]) -> bool:
    return config.get("mode") in {"workflow_api", "ai_api"} and bool(str(config.get("endpoint") or "").strip())


def call_external_optimizer(
    config: Dict[str, Any],
    title: str,
    slides: List[Dict[str, Any]],
    style_key: str,
    style_preset: Dict[str, str],
    options: Dict[str, Any],
) -> Dict[str, Any]:
    mode = config.get("mode")
    if mode == "workflow_api":
        return call_workflow_api(config, title, slides, style_key, style_preset, options)
    if mode == "ai_api":
        return call_ai_api(config, title, slides, style_key, style_preset, options)
    raise ValueError("External optimizer is disabled")


def call_workflow_api(
    config: Dict[str, Any],
    title: str,
    slides: List[Dict[str, Any]],
    style_key: str,
    style_preset: Dict[str, str],
    options: Dict[str, Any],
) -> Dict[str, Any]:
    payload = {
        "title": title,
        "selected_style": style_key,
        "style_preset": style_preset,
        "options": options,
        "ppt_content": slides,
        "page_count": len(slides),
        "expected_output": (
            "Prefer returning JSON with html_code containing a complete standalone HTML deck generated by your own code, "
            "not constrained by the platform's local fixed template. "
            "Use optimized_slides only as a fallback when you cannot return complete HTML code. "
            "Use relative extracted image src values from ppt_content images, such as assets/name.png, never absolute local paths. "
            "Arrange images according to source left/top/width/height and text density instead of using one fixed slot. "
            "Do not place images inside visible placeholder boxes; blend them into the slide layout. "
            "Keep table-like data as structured rows when possible, and include editing controls for undo, draggable images, corner resize handles, adding text boxes, and adding tables when returning html_code. "
            "The selected style is only inspiration; you may create a custom visual system, CSS, layout, animations, and page structure that best fits the PPT content. "
            "All generated or optimized slide text must be English only; translate non-English source text into English when needed. "
            "Never output generic missing-title placeholders. If a title is missing, infer a concise English title from the content or use 'Slide'. "
            "Use --- as the conceptual separator between pages when returning complete html_code or markdown-like slide source comments. "
            "Ensure a polished cover page, a table-of-contents page, and occasional transition pages between major sections. "
            "Keep each slide concise. Do not produce dense paragraph pages; split long material into multiple slides or into left/right columns and cards. "
            "When content expresses comparison, progression, problems/solutions, or parallel ideas, convert it into cards, two-column layouts, tables, or timelines rather than plain bullets. "
            "Keep the design clean: do not add repeated emoji icons to every slide. Prefer numbers, short labels, subtle lines, and geometric accents for visual guidance. "
            "If returning html_code, center the main text composition within each slide's visual safe area; do not pile titles and body content in the top-left corner. "
            "For text-only slides, use the full slide width for body content instead of squeezing all text into a narrow left column. "
            "Chapter divider slides may keep the 'Chapter XX' label smaller than the main title if needed, but the actual slide title must still be larger than 45pt. "
            "Strict title rule for AI generation: every visible slide title or section heading must use font-size larger than 45pt; use 46pt/62px or larger. Do not use any title at or below 45pt. "
            "Strict body typography rule for AI generation: normal body text, captions, table cells, labels, list items, and footnotes must use font-size larger than 26pt; use 27pt/36px or larger. Do not use normal body text at or below 26pt. "
            "Exception: previous/next navigation controls are UI chrome, not slide content; keep those buttons very small, around 7pt-9pt, with tiny padding so they do not dominate the slide. "
            "Place previous/next navigation controls away from the platform Edit HTML entry and editing toolbar; do not put navigation in the top-right or bottom-right corner where editor controls may appear. "
            "Use balanced vertical and horizontal alignment. Dense pages must reorganize text into centered cards, columns, tables, or additional slides instead of shrinking body text to 26pt or below. "
            "When there is too much text for one slide, split it into continuation slides or reorganize it into columns/cards/tables; do not rely on one tall scrollable text box to show all content. "
            "Never use scrollable text boxes or CSS such as overflow:auto/overflow-y:auto for slide body text; fit content by splitting slides, using columns/cards, and balanced typography. "
            "No text, text boxes, tables, or captions may overflow outside the 16:9 slide canvas; use max-width, max-height, overflow-wrap, and internal scrolling/clipping only when unavoidable. "
            "Text must also stay inside its own card or text box; long URLs, long words, and tables must wrap instead of spilling out. "
            "When returning html_code, provide both final modes if possible: a paged slideshow with previous/next buttons and a continuous vertical-scroll webpage version similar to the provided reference HTML. "
            "The saved/exported result must support both viewing modes: paged previous/next navigation and a continuous top-to-bottom scrolling webpage with all slides/content visible in order. "
            "Do not add visible Slide 1/Slide 2 labels in the text area; use only a small bottom-right page number. "
            "Remove original PPT page-number text boxes from slide content; standalone numbers such as 1, 2, Page 3, or 3/20 must not appear in the body. "
            "Do not add placeholder image text such as Optimized slide layout or Images intact when present."
        ),
    }
    response_json = post_json(config, wrap_workflow_payload(config, payload))
    html_code = extract_html_from_any(response_json)
    optimized_slides = extract_slides_from_any(response_json)
    if not html_code and not optimized_slides:
        raise ValueError("Workflow API response did not contain html_code/html or optimized_slides content")
    return {
        "html_code": html_code,
        "slides": optimized_slides,
        "provider": "workflow_api",
        "resultType": "html" if html_code else "slides",
        "rawSummary": summarize_response(response_json),
    }


def call_ai_api(
    config: Dict[str, Any],
    title: str,
    slides: List[Dict[str, Any]],
    style_key: str,
    style_preset: Dict[str, str],
    options: Dict[str, Any],
) -> Dict[str, Any]:
    endpoint = normalize_chat_endpoint(str(config.get("endpoint") or ""))
    ai_config = dict(config)
    ai_config["endpoint"] = endpoint
    system_prompt = (
                "You are a senior PPT-to-HTML coding agent. Return JSON only. "
                "Preferred response shape: {\"html_code\":\"<!DOCTYPE html>...\"}. "
                "Generate a complete standalone HTML/CSS/JS presentation page directly from the provided ppt_content. "
                "Do not constrain yourself to the platform's local fixed template, preset classes, or renderer structure. "
                "The selected style and style_preset are only visual inspiration; create any custom layout, CSS, animation, navigation, and page structure that best fits the content. "
                "Use optimized_slides only as a fallback if you cannot produce complete HTML code. "
                "Preserve all original meaning and important text, but you may split, "
                "group, shorten duplicated text, and add clearer section titles when helpful. "
                "Use strong presentation structure: cover, agenda/table-of-contents, concise content slides, and transition slides between major sections when helpful. "
                "All generated or optimized slide text must be English only; translate non-English source text into English when needed. "
                "Never output generic missing-title placeholders. If a title is missing, infer a concise English title from the content or use 'Slide'. "
                "When a slide contains images, keep the provided local image src values from ppt_content. "
                "Image src attributes must stay relative, for example assets/slide-001-image-1.png, never file:// or D:\\ paths. "
                "Choose layout_hints such as image-left, image-right, gallery, text-heavy, image-dominant, "
                "density-short, density-medium, density-dense, cards, two-column, timeline, agenda, transition, or visual-focus from each slide's "
                "image coordinates and amount of text; do not force every image into the same position. "
                "Every slide must have one clear visual focus: an important image, a large title/number, an icon anchor, a table, or a central card group. "
                "Keep each slide concise. Avoid dense paragraph pages; split long content or reorganize it into cards, columns, tables, or timelines. "
                "Do not add repeated emoji icons to every slide. Prefer numbers, short labels, subtle lines, and geometric accents for visual guidance. "
                "Arrange text around the center of the slide's visual safe area, not piled in the top-left corner. "
                "For text-only slides, use the full slide width for body content instead of squeezing all text into a narrow left column. "
                "Chapter divider slides may keep the 'Chapter XX' label smaller than the main title if needed, but the actual slide title must still be larger than 45pt. "
                "For html_code, include all required CSS and JS in the returned code; the platform will write your code directly to index.html after only minimal asset-path normalization. "
                "Strict title rule for AI generation: every visible slide title or section heading must use font-size larger than 45pt; use 46pt/62px or larger. Do not use any title at or below 45pt. "
                "Strict body typography rule for AI generation: normal body text, captions, table cells, labels, list items, and footnotes must use font-size larger than 26pt; use 27pt/36px or larger. Do not use normal body text at or below 26pt. "
                "Exception: previous/next navigation controls are UI chrome, not slide content; keep those buttons very small, around 7pt-9pt, with tiny padding so they do not dominate the slide. "
                "Place previous/next navigation controls away from the platform Edit HTML entry and editing toolbar; do not put navigation in the top-right or bottom-right corner where editor controls may appear. "
                "For any html_code response, CSS must enforce body text larger than 26pt and titles larger than 45pt, with centered/balanced vertical alignment. "
                "For dense text, split content across continuation slides or use columns/cards/tables; avoid putting all text into one vertical scrolling box. "
                "Never use scrollable text boxes or CSS overflow:auto/overflow-y:auto for slide body text; do not solve dense text by adding scrollbars. "
                "Ensure every text block, free text box, table, and media caption stays inside the slide viewport; do not let content overflow beyond the screen. "
                "Text must also stay inside its own card or text box; long URLs, long words, and tables must wrap instead of spilling out. "
                "Do not put page numbers, Slide labels, or square placeholder symbols inside slide titles or body text. "
                "Remove original PPT page-number text boxes from optimized text. Standalone page markers such as 1, 2, Page 3, or 3/20 must not appear as body content. "
                "Only use a small bottom-right page number marker. "
                "Keep table-like content as tables where possible. In optimized_slides, table text items may include kind:'table' and rows:[[...],[...]]. "
                "When a slide has no images, use a text-only layout. Never add placeholder image panels or text "
                "such as 'Optimized slide layout' or 'Images intact when present'. "
                "Return optimized_slides only if complete html_code is impossible."
    )
    user_prompt = json.dumps(
                {
                    "title": title,
                    "selected_style": style_key,
                    "style_preset": style_preset,
                    "options": options,
                    "ppt_content": slides,
                    "page_count": len(slides),
                    "html_requirements": [
                        "Preferred response shape: {\"html_code\":\"<!DOCTYPE html><html>...</html>\"}",
                        "The html_code should be used directly as the final page and should not depend on the platform fixed template",
                        "Alternative fallback shape only if full HTML is impossible: {\"optimized_slides\":[{\"page\":1,\"texts\":[{\"content\":\"...\",\"isTitle\":true}],\"images\":[{\"src\":\"assets/...\"}],\"layout_hints\":[\"image-right\",\"density-short\"]}]}",
                        "You may add agenda, continuation, and transition slides when needed; preserve original meaning and keep page numbers sequential",
                        "Use extracted image src paths exactly as provided and keep them relative",
                        "Adapt each slide layout to text length, image count, and original image coordinates through layout_hints",
                        "Use cards/two-column/timeline/agenda/transition/visual-focus layout_hints when the content structure calls for them",
                        "Guarantee a neat cover, table-of-contents, and transition pages for major sections when returning html_code or optimized structure",
                        "Keep per-slide text limited; split long text across slides rather than using a scrollable text box",
                        "Turn parallel, contrast, problem-solution, or progressive content into structured cards, tables, or timelines",
                        "Keep visual guidance clean; avoid repeated emoji icons and use numbers, labels, lines, or geometric accents instead",
                        "Keep text composition visually centered and balanced; do not place all text in the upper-left corner",
                        "Use the full slide width for text-only body content; do not squeeze all text into a narrow left card",
                        "All generated or optimized slide text must be English only; translate non-English source text into English when needed",
                        "Never output generic missing-title placeholders; infer a concise English title or use 'Slide'",
                        "Chapter XX labels may be smaller than the main title, but keep actual slide titles larger than 45pt",
                        "When returning html_code, enforce every visible slide title or section heading larger than 45pt; use 46pt/62px or larger",
                        "When returning html_code, enforce normal body text larger than 26pt; use 27pt/36px or larger",
                        "Do not use normal body text at or below 26pt; split content into more pages/cards/columns instead of shrinking text",
                        "Avoid scrollable mega text boxes; split dense content into continuation slides or structured columns/cards/tables",
                        "Never use scrollable text boxes or CSS overflow:auto/overflow-y:auto for normal slide body text",
                        "Prevent all text, tables, and text boxes from overflowing outside the slide canvas",
                        "Prevent text from overflowing outside its own card or text box; wrap long URLs and long words",
                        "Keep previous/next navigation buttons very small, around 7pt-9pt, because navigation buttons are UI chrome rather than slide content",
                        "Do not place previous/next navigation in the top-right or bottom-right corner; keep it away from the platform Edit HTML controls",
                        "If returning complete html_code, support both modes: paged previous/next navigation and continuous vertical webpage scrolling with all slides/content visible in order",
                        "Represent tables as {\"content\":\"A | B\\n1 | 2\",\"kind\":\"table\",\"rows\":[[\"A\",\"B\"],[\"1\",\"2\"]]} when the source contains structured data",
                        "Do not add visible page-number text to slide content; page numbers belong only in the corner marker",
                        "Remove original PPT page-number text boxes such as standalone 1, Page 2, or 2/20 from optimized_slides text",
                        "Do not invent image placeholders on slides without images",
                        "Make html_code self-contained except for relative image paths in assets/...",
                    ],
                },
                ensure_ascii=False,
    )
    payload = build_ai_payload(ai_config, system_prompt, user_prompt, temperature=0.25)
    response_json = post_json(ai_config, payload)
    html_code = extract_html_from_any(response_json)
    optimized_slides = extract_slides_from_any(response_json)
    if not html_code and not optimized_slides:
        raise ValueError("AI API response did not contain valid html_code or optimized_slides")
    return {
        "html_code": html_code,
        "slides": optimized_slides,
        "provider": "ai_api",
        "resultType": "html" if html_code else "slides",
        "rawSummary": summarize_response(response_json),
    }


def post_json(config: Dict[str, Any], payload: Dict[str, Any]) -> Dict[str, Any]:
    endpoint = normalize_endpoint_url(str(config.get("endpoint") or "").strip())
    if not endpoint:
        raise ValueError("API endpoint is empty")
    data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    headers = {
        "Content-Type": "application/json; charset=utf-8",
        "Accept": "application/json, text/plain, */*",
    }
    headers.update(parse_custom_headers(str(config.get("customHeaders") or "")))
    api_key = str(config.get("apiKey") or "").strip()
    key_header = str(config.get("apiKeyHeader") or "Authorization")
    if api_key and key_header != "none":
        prefix = str(config.get("apiKeyPrefix") or "")
        headers[key_header] = f"{prefix}{api_key}" if prefix else api_key
    timeout = effective_timeout(endpoint, config)
    direct_first = is_local_endpoint(endpoint)
    try:
        raw, content_type = execute_post(endpoint, data, headers, timeout, direct=direct_first)
    except urllib.error.HTTPError as exc:
        raw = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"API HTTP {exc.code}: {raw[:1000]}") from exc
    except (TimeoutError, socket.timeout) as exc:
        raise RuntimeError(format_timeout_error(endpoint, timeout)) from exc
    except urllib.error.URLError as exc:
        if is_timeout_error(exc):
            raise RuntimeError(format_timeout_error(endpoint, timeout)) from exc
        if should_retry_without_proxy(endpoint, exc):
            try:
                raw, content_type = execute_post(endpoint, data, headers, timeout, direct=True)
            except urllib.error.HTTPError as direct_http:
                raw = direct_http.read().decode("utf-8", errors="replace")
                raise RuntimeError(f"API HTTP {direct_http.code}: {raw[:1000]}") from direct_http
            except (TimeoutError, socket.timeout) as direct_timeout:
                raise RuntimeError(format_timeout_error(endpoint, timeout, retried_direct=True)) from direct_timeout
            except urllib.error.URLError as direct_exc:
                if is_timeout_error(direct_exc):
                    raise RuntimeError(format_timeout_error(endpoint, timeout, retried_direct=True)) from direct_exc
                raise RuntimeError(format_url_error(endpoint, direct_exc, retried_direct=True)) from direct_exc
        else:
            raise RuntimeError(format_url_error(endpoint, exc, retried_direct=False)) from exc

    if "json" in content_type.lower():
        return json.loads(raw)
    stripped = raw.strip()
    if stripped.startswith("{") or stripped.startswith("["):
        return json.loads(stripped)
    if looks_like_html_document(stripped):
        return {"html_code": stripped}
    return {"text": stripped}


def execute_post(
    endpoint: str,
    data: bytes,
    headers: Dict[str, str],
    timeout: int,
    direct: bool = False,
) -> tuple[str, str]:
    request = urllib.request.Request(endpoint, data=data, headers=headers, method="POST")
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({})) if direct else None
    open_fn = opener.open if opener else urllib.request.urlopen
    with open_fn(request, timeout=timeout) as response:
        raw = response.read().decode("utf-8", errors="replace")
        content_type = response.headers.get("Content-Type", "")
    return raw, content_type


def normalize_endpoint_url(endpoint: str) -> str:
    endpoint = endpoint.strip()
    if not endpoint:
        return ""
    if re.match(r"^https?://", endpoint, re.IGNORECASE):
        return endpoint
    host = endpoint.split("/", 1)[0].strip("[]").split(":", 1)[0].lower()
    if (
        host in {"localhost", "127.0.0.1", "::1"}
        or host.startswith("192.168.")
        or host.startswith("10.")
        or re.match(r"^172\.(1[6-9]|2\d|3[0-1])\.", host)
    ):
        return f"http://{endpoint}"
    return f"https://{endpoint}"


def normalize_chat_endpoint(endpoint: str) -> str:
    endpoint = normalize_endpoint_url(endpoint).rstrip("/")
    if endpoint.endswith("/chat/completions"):
        return endpoint
    if endpoint.endswith("/responses"):
        return endpoint
    if endpoint.endswith("/v1") or endpoint.endswith("/api/v3"):
        return endpoint + "/chat/completions"
    return endpoint


def endpoint_uses_responses(endpoint: str) -> bool:
    return normalize_endpoint_url(endpoint).rstrip("/").endswith("/responses")


def build_ai_payload(config: Dict[str, Any], system_prompt: str, user_prompt: str, temperature: float | None = None) -> Dict[str, Any]:
    model = config.get("model") or DEFAULT_INTEGRATION["model"]
    if endpoint_uses_responses(str(config.get("endpoint") or "")):
        combined_prompt = f"{system_prompt.strip()}\n\nUser input JSON:\n{user_prompt.strip()}"
        return {
            "model": model,
            "input": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "input_text",
                            "text": combined_prompt,
                        }
                    ],
                }
            ],
        }
    payload: Dict[str, Any] = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    }
    if temperature is not None:
        payload["temperature"] = temperature
    return payload


def should_retry_without_proxy(endpoint: str, exc: urllib.error.URLError) -> bool:
    if is_local_endpoint(endpoint) or not is_connection_refused(exc):
        return False
    proxy = proxy_for_endpoint(endpoint)
    return bool(proxy and is_loopback_proxy(proxy))


def proxy_for_endpoint(endpoint: str) -> str:
    scheme = urllib.parse.urlparse(endpoint).scheme.lower()
    proxies = urllib.request.getproxies()
    return str(proxies.get(scheme) or proxies.get("all") or "")


def is_loopback_proxy(proxy_url: str) -> bool:
    if not proxy_url:
        return False
    normalized = proxy_url if "://" in proxy_url else f"http://{proxy_url}"
    host = (urllib.parse.urlparse(normalized).hostname or "").lower()
    return host in {"127.0.0.1", "localhost", "::1"}


def is_local_endpoint(endpoint: str) -> bool:
    host = (urllib.parse.urlparse(endpoint).hostname or "").lower()
    return host in {"127.0.0.1", "localhost", "::1"}


def is_doubao_endpoint(endpoint: str) -> bool:
    host = (urllib.parse.urlparse(endpoint).hostname or "").lower()
    return "volces.com" in host or "volcengine" in host


def effective_timeout(endpoint: str, config: Dict[str, Any]) -> int:
    timeout = normalize_timeout(config.get("timeoutSec"))
    if is_doubao_endpoint(endpoint):
        return max(timeout, 300)
    return timeout


def is_timeout_error(exc: BaseException) -> bool:
    reason = getattr(exc, "reason", None)
    text = f"{exc} {reason}".lower()
    return (
        isinstance(exc, TimeoutError)
        or isinstance(reason, (TimeoutError, socket.timeout))
        or "timed out" in text
        or "read operation timed out" in text
        or "timeout" in text
    )


def format_timeout_error(endpoint: str, timeout: int, retried_direct: bool = False) -> str:
    parsed = urllib.parse.urlparse(endpoint)
    host = parsed.netloc or endpoint
    retry_note = " after direct retry" if retried_direct else ""
    return (
        f"API request timed out{retry_note} while waiting for {host} after {timeout}s. "
        "Large PPT files and Doubao/Ark generation can take several minutes. "
        "Try again, reduce the PPT size, or increase Timeout (sec) up to 600 in Advanced connection settings."
    )


def is_connection_refused(exc: BaseException) -> bool:
    reason = getattr(exc, "reason", None)
    text = f"{exc} {reason}".lower()
    return (
        isinstance(reason, ConnectionRefusedError)
        or "10061" in text
        or "actively refused" in text
        or "connection refused" in text
        or "目标计算机积极拒绝" in text
    )


def format_url_error(endpoint: str, exc: urllib.error.URLError, retried_direct: bool = False) -> str:
    parsed = urllib.parse.urlparse(endpoint)
    host = parsed.netloc or endpoint
    reason = getattr(exc, "reason", exc)
    if is_connection_refused(exc):
        if is_local_endpoint(endpoint):
            return (
                f"API request failed: cannot connect to local endpoint {host}. "
                "Please start the workflow/API service on that port, or correct the Endpoint."
            )
        proxy = proxy_for_endpoint(endpoint)
        if proxy and is_loopback_proxy(proxy) and not retried_direct:
            return (
                f"API request failed: the Windows proxy {proxy} refused the connection while connecting to {host}. "
                "Start that proxy app, disable the system proxy, or retry after the platform bypasses the proxy."
            )
        if retried_direct:
            return (
                f"API request failed: the local proxy refused the connection and direct retry to {host} also failed. "
                f"Reason: {reason}"
            )
    return f"API request failed while connecting to {host}: {reason}"


def wrap_workflow_payload(config: Dict[str, Any], payload: Dict[str, Any]) -> Dict[str, Any]:
    payload_mode = config.get("workflowPayload") or "flat"
    if payload_mode == "input":
        return {"input": payload}
    if payload_mode == "dify":
        return {
            "inputs": payload,
            "response_mode": "blocking",
            "user": "ppt-html-studio",
        }
    return payload


def parse_custom_headers(raw: str) -> Dict[str, str]:
    raw = raw.strip()
    if not raw:
        return {}
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        parsed = {}
        for line in raw.splitlines():
            line = line.strip().rstrip("\\").strip()
            header_match = re.match(r"^-H\s+['\"]?([^:'\"]+)\s*:\s*(.*?)['\"]?\s*$", line)
            if header_match:
                key, value = header_match.groups()
            elif ":" in line:
                key, value = line.split(":", 1)
            else:
                continue
            key = key.strip()
            value = value.strip().strip("'\"")
            if not is_valid_header_name(key) or not value:
                continue
            parsed[key] = value
    if not isinstance(parsed, dict):
        return {}
    return {
        str(key).strip(): str(value)
        for key, value in parsed.items()
        if is_valid_header_name(str(key).strip()) and str(value).strip()
    }


def is_valid_header_name(name: str) -> bool:
    return bool(re.fullmatch(r"[!#$%&'*+.^_`|~0-9A-Za-z-]+", name or ""))


def extract_html_from_any(value: Any) -> str:
    if isinstance(value, str):
        return extract_html(value)
    if isinstance(value, dict):
        for key in ("html_code", "html", "content", "result", "data", "output", "outputs", "output_text", "answer", "text", "body"):
            if key in value:
                found = extract_html_from_any(value[key])
                if found:
                    return found
        choices = value.get("choices")
        if isinstance(choices, list) and choices:
            for choice in choices:
                found = extract_html_from_any(choice)
                if found:
                    return found
        message = value.get("message")
        if isinstance(message, dict):
            return extract_html_from_any(message.get("content"))
    if isinstance(value, list):
        for item in value:
            found = extract_html_from_any(item)
            if found:
                return found
    return ""


def extract_html(text: str) -> str:
    text = text.strip()
    if text.startswith("{") or text.startswith("["):
        try:
            return extract_html_from_any(json.loads(text))
        except json.JSONDecodeError:
            pass
    fenced = re.search(r"```(?:html)?\s*(.*?)```", text, flags=re.IGNORECASE | re.DOTALL)
    if fenced:
        text = fenced.group(1).strip()
    start = text.lower().find("<!doctype")
    if start < 0:
        start = text.lower().find("<html")
    if start >= 0:
        end = text.lower().rfind("</html>")
        if end >= 0:
            return text[start : end + len("</html>")].strip()
        return text[start:].strip()
    if looks_like_html_fragment(text):
        return wrap_html_fragment(text)
    return text if looks_like_html_document(text) else ""


def looks_like_html_document(text: str) -> bool:
    lowered = text.strip().lower()
    return "<!doctype" in lowered or "<html" in lowered


def looks_like_html_fragment(text: str) -> bool:
    lowered = text.strip().lower()
    if not lowered or lowered.startswith("{") or lowered.startswith("["):
        return False
    tags = (
        "<style",
        "<script",
        "<main",
        "<section",
        "<article",
        "<div",
        "<body",
        "<h1",
        "<figure",
        "<img",
        "<table",
    )
    return any(tag in lowered for tag in tags) and bool(re.search(r"</?[a-z][\w:-]*(?:\s|>|/>)", lowered))


def wrap_html_fragment(fragment: str) -> str:
    lowered = fragment.lower()
    title = "AI Generated Presentation"
    style_blocks = "\n".join(re.findall(r"<style\b[^>]*>.*?</style>", fragment, flags=re.IGNORECASE | re.DOTALL))
    script_blocks = "\n".join(re.findall(r"<script\b[^>]*>.*?</script>", fragment, flags=re.IGNORECASE | re.DOTALL))
    body = re.sub(r"<style\b[^>]*>.*?</style>", "", fragment, flags=re.IGNORECASE | re.DOTALL)
    body = re.sub(r"<script\b[^>]*>.*?</script>", "", body, flags=re.IGNORECASE | re.DOTALL).strip()
    if "<body" in lowered:
        body_match = re.search(r"<body\b[^>]*>(.*?)</body>", fragment, flags=re.IGNORECASE | re.DOTALL)
        if body_match:
            body = body_match.group(1).strip()
    return (
        "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        f"  <title>{title}</title>\n"
        f"{style_blocks}\n"
        "</head>\n"
        f"<body>\n{body}\n{script_blocks}\n</body>\n"
        "</html>"
    )


def extract_slides_from_any(value: Any) -> List[Dict[str, Any]]:
    if isinstance(value, str):
        text = value.strip()
        fenced = re.search(r"```(?:json)?\s*(.*?)```", text, flags=re.IGNORECASE | re.DOTALL)
        if fenced:
            text = fenced.group(1).strip()
        if text.startswith("{") or text.startswith("["):
            try:
                return extract_slides_from_any(json.loads(text))
            except json.JSONDecodeError:
                return []
        return []
    if isinstance(value, list):
        if all(isinstance(item, dict) for item in value) and any("page" in item for item in value):
            return value
        for item in value:
            found = extract_slides_from_any(item)
            if found:
                return found
        return []
    if isinstance(value, dict):
        for key in ("optimized_slides", "slides", "ppt_content", "pages"):
            found = extract_slides_from_any(value.get(key))
            if found:
                return found
        for key in ("content", "result", "data", "output", "outputs", "output_text", "answer", "text", "body", "html_code", "html"):
            if key in value:
                found = extract_slides_from_any(value[key])
                if found:
                    return found
        choices = value.get("choices")
        if isinstance(choices, list):
            for choice in choices:
                found = extract_slides_from_any(choice)
                if found:
                    return found
        message = value.get("message")
        if isinstance(message, dict):
            return extract_slides_from_any(message.get("content"))
    return []


def summarize_response(value: Any) -> Dict[str, Any]:
    if isinstance(value, dict):
        return {"keys": list(value.keys())[:20], "receivedAt": int(time.time())}
    return {"type": type(value).__name__, "receivedAt": int(time.time())}


def build_test_payload(config: Dict[str, Any]) -> Dict[str, Any]:
    if config.get("mode") == "ai_api":
        return build_ai_payload(
            config,
            "Return JSON only.",
            "Return {\"ok\":true,\"service\":\"ppt-html-studio\"}.",
            temperature=0,
        )
    payload = {
        "type": "health_check",
        "service": "ppt-html-studio",
        "expected_output": "Return JSON that confirms the workflow endpoint is reachable.",
    }
    return wrap_workflow_payload(config, payload)
